
export const DEFAULT_DICTIONARY = [
  'time',
  'people',
  'world',
  'system',
  'number',
  'group',
  'problem',
  'method',
  'result',
  'client',
  'server',
  'design',
  'feature',
  'random',
  'typing',
  'react',
  'state',
  'effect',
  'render',
  'update',
  'branch',
  'deploy',
  'build',
  'merge',
  'commit',
  'review',
  'value',
  'input',
  'output',
  'button',
  'layout',
  'theme',
  'helper',
  'window',
  'event',
  'reason',
  'future',
  'simple',
  'string',
  'mobile',
  'screen',
  'color',
  'smooth',
  'target',
  'format',
  'speed',
  'error',
  'correct',
  'finish',
  'restart',
] as const;

export function generateWords(dictionary: readonly string[], count: number): string[] {
  return Array.from({ length: count }, () => {
    const randomIndex = Math.floor(Math.random() * dictionary.length);
    return dictionary[randomIndex];
  });
}
